name: CI micro-ROS Zephyr module

on:
  pull_request:
    branches: 
      - '**'

jobs:

  micro_ros_zephyr_module:
    runs-on: ubuntu-latest
    container: ubuntu:20.04    

    steps:
      - uses: actions/checkout@v2
        with:
          path: micro_ros_zephyr_module

      - name: Dependencies
        shell: bash
        run: |
          apt update
          export DEBIAN_FRONTEND=noninteractive
          apt install -y --no-install-recommends lsb-release git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget curl gnupg2 \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev
          pip3 install --user -U west
          export PATH=~/.local/bin:/github/home/.local/bin:"$PATH"
          west init zephyrproject
          cd zephyrproject
          west update
          west zephyr-export
          pip3 install --user -r zephyr/scripts/requirements.txt
          cd ..
          export TOOLCHAIN_VERSION=0.11.4
          export TOOLCHAIN_FILE_NAME=zephyr-toolchain-arm-$TOOLCHAIN_VERSION-setup.run
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v$TOOLCHAIN_VERSION/$TOOLCHAIN_FILE_NAME
          chmod +x $TOOLCHAIN_FILE_NAME
          ./$TOOLCHAIN_FILE_NAME -- -rc -y -d $(pwd)/zephyr-sdk
          rm -rf $TOOLCHAIN_FILE_NAME
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=$(pwd)/zephyr-sdk
          source zephyrproject/zephyr/zephyr-env.sh
          # Installing micro-ROS prerequisites
          sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
          apt update
          apt install -y python3-colcon-common-extensions
          pip3 install catkin_pkg lark-parser empy
          # Building the app
          west build -b disco_l475_iot1 micro_ros_zephyr_module
