name: CI

on:
  pull_request:
    branches:
      - '**'

jobs:

  micro_ros_zephyr_module:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    strategy:
      fail-fast: false
      matrix:
        zephyr_version: ["zephyr-v2.4.0", "zephyr-v2.5.0", "zephyr-v2.6.0"]
        include:
          - zephyr_version: zephyr-v2.4.0
            zephyr_sdk: 0.11.4
            sdk_filename: zephyr-toolchain-arm-$TOOLCHAIN_VERSION-setup.run
          - zephyr_version: zephyr-v2.5.0
            zephyr_sdk: 0.11.4
            sdk_filename: zephyr-toolchain-arm-$TOOLCHAIN_VERSION-setup.run
          - zephyr_version: zephyr-v2.6.0
            zephyr_sdk: 0.12.4
            sdk_filename: zephyr-toolchain-arm-$TOOLCHAIN_VERSION-x86_64-linux-setup.run
    steps:
      - uses: actions/checkout@v2
        with:
          path: micro_ros_zephyr_module

      - name: Dependencies
        shell: bash
        run: |
          apt update
          export DEBIAN_FRONTEND=noninteractive
          apt install -y --no-install-recommends git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget curl gnupg2 \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev
          pip3 install --user -U west
          export PATH=~/.local/bin:/github/home/.local/bin:"$PATH"
          west init zephyrproject
          cd zephyrproject
          cd zephyr
          git checkout ${{ matrix.zephyr_version }}
          cd ..
          west update
          west zephyr-export
          pip3 install --user -r zephyr/scripts/requirements.txt
          cd ..
          export TOOLCHAIN_VERSION=${{ matrix.zephyr_sdk }}
          export TOOLCHAIN_FILE_NAME=${{ matrix.sdk_filename }}
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v$TOOLCHAIN_VERSION/$TOOLCHAIN_FILE_NAME
          chmod +x $TOOLCHAIN_FILE_NAME
          yes | ./$TOOLCHAIN_FILE_NAME -- -rc -y -d $(pwd)/zephyr-sdk || :
          rm -rf $TOOLCHAIN_FILE_NAME
          export ZEPHYR_TOOLCHAIN_VARIANT=zephyr
          export ZEPHYR_SDK_INSTALL_DIR=$(pwd)/zephyr-sdk
          source zephyrproject/zephyr/zephyr-env.sh
          # Installing micro-ROS prerequisites
          pip3 install catkin_pkg lark-parser empy colcon-common-extensions
          # Building the app
          west build -b adafruit_feather_stm32f405 micro_ros_zephyr_module
