name: Nightly

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron:  '0 4 * * *'

jobs:

  nightly_micro_ros_zephyr_module:
    runs-on: ubuntu-latest
    container: 
      image: zephyrprojectrtos/ci:v0.26.17
      options: --user root
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    strategy:
      fail-fast: false
      matrix:
<<<<<<< HEAD
        zephyr_version: ["zephyr-v3.1.0", "zephyr-v2.7.2"]
        distro: ["iron", "humble", "rolling"]
=======
        zephyr_version: ["v4.0.0", "v4.1.0"]
        distro: ["rolling", "jazzy", "humble"]
>>>>>>> 7cbe6da (updates project to work with zephyr v4.0.x (#146))
        include:
          - distro: rolling
            branch: rolling
<<<<<<< HEAD
          - distro: humble
            branch: humble
          - zephyr_version: zephyr-v2.7.2
            zephyr_sdk: 0.14.2
            sdk_filename: zephyr-sdk-$TOOLCHAIN_VERSION\_linux-x86_64_minimal.tar.gz
          - zephyr_version: zephyr-v3.1.0
            zephyr_sdk: 0.14.2
            sdk_filename: zephyr-sdk-$TOOLCHAIN_VERSION\_linux-x86_64_minimal.tar.gz
=======
          - distro: jazzy
            branch: jazzy
          - distro: humble
            branch: humble
>>>>>>> 7cbe6da (updates project to work with zephyr v4.0.x (#146))
    steps:
      - uses: actions/checkout@v4
        with:
          path: micro_ros_zephyr_module
          ref: ${{ matrix.branch }}

      - name: Build
        shell: bash
        run: |
          # Zephyr setup
          apt -y update
          west init 
          cd zephyr
          git checkout ${{ matrix.zephyr_version }}
          cd ..
          west update --narrow

          # Installing micro-ROS prerequisites
          pip3 install catkin_pkg lark-parser empy colcon-common-extensions

          # Build with Serial USB transport
          west build -b disco_l475_iot1 $GITHUB_WORKSPACE/micro_ros_zephyr_module -p -- -DCONFIG_MICROROS_TRANSPORT_SERIAL_USB=y

          # Build with Serial transport
          west build -b disco_l475_iot1 $GITHUB_WORKSPACE/micro_ros_zephyr_module -p -- -DCONFIG_MICROROS_TRANSPORT_SERIAL=y
